initial_pose:
  x: -2.0
  y: -0.5
  yaw: 0.0

waypoints:
  - x: -1.4
    y: -0.5
    yaw: 0.0
  - x: -1.4
    y: 0.1
    yaw: 1.5708
  - x: -2.0
    y: 0.1
    yaw: 3.1416
  - x: -2.0
    y: -0.5
    yaw: -1.5708
